
from __future__ import print_function

import csv
import requests
import requests_cache

# Cache requests on disk.
requests_cache.install_cache(
  "data/cache",
  allowable_codes=range(1000), # Just cache everything (we care about 200, 301, 302).
  backend="sqlite"
)


def load(url):

  # print("\n###", url)

  r = requests.get(url, allow_redirects=False)

  print("status:", r.status_code)

  for key in ["strict-transport-security",
              "location",
              "pragma",
              "cache-control"]:
    try:
      print(key + ":", r.headers[key])
    except:
      pass

def go(base_url):
  for protocol in ["http", "https"]:
    for subdomain in ["www.", ""]:
      load(protocol + "://" + subdomain + base_url)


# Chromium STS Headliners
go("google.com")
go("paypal.com")
go("twitter.com")
go("simple.com")
go("linode.com")
go("stripe.com")
go("lastpass.com")

# Miscellaneous
go("dropbox.com")
go("paypal.com")
go("mega.co.nz")
go("lastpass.com")
go("stripe.com")
go("squareup.com")
go("torproject.org")
go("bugzilla.mozilla.org")
go("braintreepayments.com")
go("greplin.com")

# Personal Interest
go("worldcubeassociation.org")

# From Chrome preload list
go("www.paypal.com")
go("paypal.com")
go("www.elanex.biz")
go("jottit.com")
go("sunshinepress.org")
go("www.noisebridge.net")
go("neg9.org")
go("riseup.net")
go("factor.cc")
go("members.mayfirst.org")
go("support.mayfirst.org")
go("id.mayfirst.org")
go("lists.mayfirst.org")
go("webmail.mayfirst.org")
go("roundcube.mayfirst.org")
go("aladdinschools.appspot.com")
go("ottospora.nl")
go("www.paycheckrecords.com")
go("lastpass.com")
go("www.lastpass.com")
go("keyerror.com")
go("entropia.de")
go("www.entropia.de")
go("romab.com")
go("logentries.com")
go("www.logentries.com")
go("stripe.com")
go("cloudsecurityalliance.org")
go("login.sapo.pt")
go("mattmccutchen.net")
go("betnet.fr")
go("uprotect.it")
go("squareup.com")
go("square.com")
go("cert.se")
go("crypto.is")
go("include_subdomains")
go("linx.net")
go("dropcam.com")
go("www.dropcam.com")
go("ebanking.indovinabank.com.vn")
go("epoxate.com")
go("torproject.org")
go("blog.torproject.org")
go("check.torproject.org")
go("www.torproject.org")
go("dist.torproject.org")
go("www.moneybookers.com")
go("ledgerscope.net")
go("www.ledgerscope.net")
go("app.recurly.com")
go("api.recurly.com")
go("greplin.com")
go("www.greplin.com")
go("luneta.nearbuysystems.com")
go("ubertt.org")
go("pixi.me")
go("grepular.com")
go("mydigipass.com")
go("www.mydigipass.com")
go("developer.mydigipass.com")
go("www.developer.mydigipass.com")
go("sandbox.mydigipass.com")
go("www.sandbox.mydigipass.com")
go("crypto.cat")
go("bigshinylock.minazo.net")
go("crate.io")
go("twitter.com")
go("www.twitter.com")
go("braintreegateway.com")
go("braintreepayments.com")
go("www.braintreepayments.com")
go("emailprivacytester.com")
go("business.medbank.com.mt")
go("arivo.com.br")
go("www.apollo-auto.com")
go("www.cueup.com")
go("jitsi.org")
go("www.jitsi.org")
go("download.jitsi.org")
go("sol.io")
go("irccloud.com")
go("www.irccloud.com")
go("alpha.irccloud.com")
go("passwd.io")
go("browserid.org")
go("login.persona.org")
go("neonisi.com")
go("www.neonisi.com")
go("shops.neonisi.com")
go("piratenlogin.de")
go("howrandom.org")
go("intercom.io")
go("api.intercom.io")
go("www.intercom.io")
go("fatzebra.com.au")
go("csawctf.poly.edu")
go("makeyourlaws.org")
go("www.makeyourlaws.org")
go("iop.intuit.com")
go("surfeasy.com")
go("www.surfeasy.com")
go("packagist.org")
go("lookout.com")
go("www.lookout.com")
go("mylookout.com")
go("www.mylookout.com")
go("dm.lookout.com")
go("dm.mylookout.com")
go("itriskltd.com")
go("stocktrade.de")
go("openshift.redhat.com")
go("therapynotes.com")
go("www.therapynotes.com")
go("wiz.biz")
go("my.onlime.ch")
go("webmail.onlime.ch")
go("crm.onlime.ch")
go("www.gov.uk")
go("silentcircle.com")
go("silentcircle.org")
go("serverdensity.io")
go("my.alfresco.com")
go("webmail.gigahost.dk")
go("paymill.com")
go("paymill.de")
go("gocardless.com")
go("espra.com")
go("zoo24.de")
go("mega.co.nz")
go("api.mega.co.nz")
go("lockify.com")
go("writeapp.me")
go("bugzilla.mozilla.org")
go("members.nearlyfreespeech.net")
go("ssl.panoramio.com")
go("kiwiirc.com")
go("pay.gigahost.dk")
go("controlcenter.gigahost.dk")
go("simple.com")
go("www.simple.com")
go("fj.simple.com")
go("api.simple.com")
go("bank.simple.com")
go("bassh.net")
go("sah3.net")
go("grc.com")
go("www.grc.com")
go("linode.com")
go("www.linode.com")
go("manager.linode.com")
go("blog.linode.com")
go("library.linode.com")
go("forum.linode.com")
go("p.linode.com")
go("paste.linode.com")
go("pastebin.linode.com")
go("inertianetworks.com")
go("carezone.com")
go("conformal.com")
go("cyphertite.com")
go("logotype.se")
go("bccx.com")
go("launchkey.com")
go("carlolly.co.uk")
go("www.cyveillance.com")
go("blog.cyveillance.com")
go("whonix.org")
go("blueseed.co")
go("forum.quantifiedself.com")
go("shodan.io")
go("rapidresearch.me")
go("surkatty.org")
go("securityheaders.com")
go("haste.ch")
go("mudcrab.us")
go("mediacru.sh")
go("lolicore.ch")
go("cloudns.com.au")
go("oplop.appspot.com")
go("bcrook.com")
go("wiki.python.org")
go("lumi.do")
go("appseccalifornia.org")
go("crowdcurity.com")
go("saturngames.co.uk")
go("strongest-privacy.com")
